// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6e-kvECUWgnWN80qNN9PinZTU1ZgL72c',
    appId: '1:1049596370520:web:8a3b05c314e4ba862a742d',
    messagingSenderId: '1049596370520',
    projectId: 'studifyynew',
    authDomain: 'studifyynew.firebaseapp.com',
    storageBucket: 'studifyynew.appspot.com',
    measurementId: 'G-018Z97CFBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRnMCYxUNedECDUZ1830ua9Y0n_L6OgZc',
    appId: '1:1049596370520:android:12a4f1f3f4d88cec2a742d',
    messagingSenderId: '1049596370520',
    projectId: 'studifyynew',
    storageBucket: 'studifyynew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBADhVX0qCQ1q-BC0_I_TREU5v5-HWmULA',
    appId: '1:1049596370520:ios:19ecbc99565c23af2a742d',
    messagingSenderId: '1049596370520',
    projectId: 'studifyynew',
    storageBucket: 'studifyynew.appspot.com',
    androidClientId: '1049596370520-mal2jlnuq1hrclihh28jl9d9ai7jhbul.apps.googleusercontent.com',
    iosBundleId: 'com.example.technicianpartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBADhVX0qCQ1q-BC0_I_TREU5v5-HWmULA',
    appId: '1:1049596370520:ios:aa1dbdcae8adf7392a742d',
    messagingSenderId: '1049596370520',
    projectId: 'studifyynew',
    storageBucket: 'studifyynew.appspot.com',
    androidClientId: '1049596370520-mal2jlnuq1hrclihh28jl9d9ai7jhbul.apps.googleusercontent.com',
    iosBundleId: 'com.example.technicianpartner.RunnerTests',
  );
}
